version: '3'
services:
  db:
    container_name: agl-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    container_name: agl-web
    build: .
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app