# .github/workflows/ci.yml

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.31.1
        with:
          ruby-version: 2.6.5
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build and run rails tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          PGUSER: postgres
          PGPASSWORD: postgres
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
          bundle exec rails test
      - name: Cypress run
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          PGUSER: postgres
          PGPASSWORD: postgres
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        with:
          start: bin/rails server -e test -p 5017
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:5017'
        run: |
          yarn cypress open --project ./test
