# .github/workflows/ci.yml

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - name: Set Environment Variables
        id: set_github_env
        run: |
          echo "DATABASE_URL=postgres://postgres:@localhost:5432/test" >> $GITHUB_ENV
          echo "PGUSER=postgres" >> $GITHUB_ENV
          echo "PGPASSWORD=postgres" >> $GITHUB_ENV
          echo "REDIS_URL=redis://localhost:6379/0" >> $GITHUB_ENV
          echo "RAILS_ENV=test" >> $GITHUB_ENV
          echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.66.1
        with:
          ruby-version: 2.6.5
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Cache Cypress Installation
        uses: actions/cache@preview
        with:
          path: /home/runner/.cache/Cypress/5.0.0/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('/home/runner/.cache/Cypress/5.0.0/Cypress') }}
          restore-keys: |
            ${{ runner.os }}-cypress-
      - name: Build and run rails tests
        # env:
          # DATABASE_URL: postgres://postgres:@localhost:5432/test
          # PGUSER: postgres
          # PGPASSWORD: postgres
          # REDIS_URL: redis://localhost:6379/0
          # RAILS_ENV: test
          # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          bundle config path vendor/bundle
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
          bundle exec rails test
      - name: Fix watched files problem
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p 
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.5
        with:
          install: false
          build: npx cypress install
          start: bundle exec rails server -e test -p 5017
          wait-on: http://localhost:5017
          command:  yarn cypress run --project ./test
        # env:
        #   DATABASE_URL: postgres://postgres:@localhost:5432/test
        #   PGUSER: postgres
        #   PGPASSWORD: postgres
        #   REDIS_URL: redis://localhost:6379/0
        #   RAILS_ENV: test
        #   RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      - name: Store Cypress Screenshots on Failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: test/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - name: Store Cypress Videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: test/cypress/videos